sudo: required
services: 
  - docker

before_install:
  - docker build -t ethanmarch/docker-react-demo -f Dockerfile.dev .

language: generic

script:
  - docker run -e CI=true ethanmarch/docker-react-demo npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-demo"
  env: "DockerReactDemo-env"
  bucket_name: "elasticbeanstalk-us-east-1-391957845137"
  bucket_path: "docker-react-demo"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY